name: second_hand
description: A new Flutter project that buy and share things


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Ions
  cupertino_icons: ^1.0.2

  # for google fonts
  google_fonts: ^3.0.1

  #for svg images
  flutter_svg: ^1.1.0

  #intro screen
  intro_slider: ^3.0.5

  #for block pattern
  rxdart: ^0.27.4


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/


